config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    namespace :admin do
      resources :posts do
        resources :comments, only: [:destroy, :show, :update, :edit] 
        end
    end
      resources :posts, only: %i[:index] do
          resources :comments, only: [:index, :create]
      end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: {minimum: 5}
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 5}
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
    validates :first_name, presence: true, length: {minimum: 2}
    validates :second_name, presence: true, length: {minimum: 5}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
end

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < ApplicationController
    before_action :comment_find, :authenticate_user!, :admin_acces
    before_action :post_find, only: %i[update show edit destroy]

    def show
    end

    def edit
      @admin = :admin
    end

    def destroy
      if @comment.destroy
        flash[:success] = "Comment Deleted"
        render 'admin/posts/show'
      else
        render :edit
      end
    end

    def update
      if @comment.update(comment_params)
        flash[:success] = "Comment Updated"
        render 'admin/posts/show'
      else
        render :edit
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def comment_find
      @comment = Comment.find(params[:id])
    end

    def post_find
      @post = Post.find(params[:post_id])
    end

    def admin_acces
      unless current_user && current_user.status?
        flash[:alert] = 'Доступ запрещен.'
        redirect_to root_path
      end
    end

  end

end

app/controllers/admin/posts_controller.rb
module Admin  
  class PostsController < ApplicationController
      before_action :find_post, only: %i[update show edit destroy]
      before_action :authenticate_user!, :admin_acces

      def index
        @posts = Post.all
        
      end

      def update
        if @post.update(post_params)
          flash[:success] = "Post Updated"
          redirect_to admin_posts_path
        else
          render :edit
        end
      end

      def new
        @post = Post.new
      end

      

      def create
        @user = current_user
        @post = @user.posts.new(post_params)
        if @post.save
          flash[:success] = "Post Created"
          redirect_to admin_posts_path
        else
          render :new
        end
      end

      def edit
      end

      def show
      end

      def destroy
        if @post.destroy
          flash[:success] = "Post Deleted"
          redirect_to admin_posts_path
        else
          render :edit
        end
      end

      private

      def find_post
        @post = Post.find(params[:id])
      end


      def post_params
        params.require(:post).permit(:body, :title)
      end

      def admin_acces
        unless current_user && current_user.status?
          flash[:alert] = 'Доступ запрещен.'
          redirect_to root_path
        end
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :second_name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :post_find, only: %i[index create]
  before_action :authenticate_user!, only: %i[create]

  def index
    @comment = Comment.new 
    @comments = @post.comments.order create_at:(:desc)
  end
  
  def create
    @user = current_user
    @comment = @post.comments.new(comment_params)
    @comment.user = @user
    if @comment.save
      redirect_to post_comments_path
      flash[:success] = "Comment created!"
    else
      render :index
    end
  end
  

  def comment_params

    params.require(:comment).permit(:body)
  end



   def post_find
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  


end

app/views/admin/comments/edit.html.erb
<div>
  <ul>
    <li>
      <p><%= @comment.body %></p>
    </li>
  </ul>
  <p><%= @comment.user.first_name %> <%= @comment.user.second_name %></p>
</div>
<div>
<%= render 'shared/form'%>
</div>

app/views/admin/comments/show.html.erb
<div>
  <ul>
    <li>
      <p><%= @comment.body %></p>
    </li>
  </ul>
  <p><%= @comment.user.first_name %> <%= @comment.user.second_name %></p>
  <div>
    <%= link_to "Update post", edit_admin_post_comment_path(@post, @comment) %>
    <%= button_to "Delete post", admin_post_comment_path(@post, @comment), method: :delete, confirm: "Are you shure?" %>
  </div>

app/views/admin/posts/_form.html.erb
<%= render 'shared/errors', object: @post%>
<%= form_with model: [:admin, @post] do |c| %>
  <%= c.label :title, 'title' %>
  <%= c.text_field :title %>

  <%= c.label :body, 'body' %>
  <%= c.text_field :body %>

  <!-- Кнопка отправки формы -->
  <%= c.submit 'Отправить' %>
<% end %>

app/views/admin/posts/edit.html.erb
<div>
  <ul>
      <li>
        <h2><%= @post.title %></h2>
      </li>
      <li>
        <p><%= @post.body %></p>
      </li>
      <p><%= @post.user.first_name %> <%= @post.user.second_name %></p>
  </ul>
</div>
<div>
<%= render 'form'%>
</div>

app/views/admin/posts/index.html.erb
<h2> <%= flash[:success] %> </h2>
<h1> Welcome to Admin panel for PostsV2 </h1>
<div>
  
  <ul>
    <% @posts.each do |p| %>
      <li>
        <h2> <%= p.title %></h2>
        <p> <%= p.body %> </p> 
      </li>
      <p> <%= p.user.first_name %>  <%= p.user.second_name %> </p> 
      <div>
      <%= link_to "Show comments", admin_post_path(p) %>
      </div>
    <% end %>
  </ul>
</div>

app/views/admin/posts/new.html.erb
<h1> Create Post </h1>
<%= render 'form'%>

app/views/admin/posts/show.html.erb
<div>
  <h2> <%= flash[:success] %> </h2>
  <ul>
      <li>
        <h2><%= @post.title %></h2>
      </li>
      <li>
        <p><%= @post.body %></p>
      </li>
      <p><%= @post.user.first_name %> <%= @post.user.second_name %></p>
  </ul>
  <div>
    <%= link_to "Update post", edit_admin_post_path(@post) %>
    <%= button_to "Delete post", admin_post_path(@post), method: :delete, confirm: "Are you shure?" %>
  </div>
  <ul>
    <h2> See comments </h2>
    <% @post.comments.each do |comment| %>
    <li>
      <p><%= comment.body %></p>
    </li>
    <p><%= comment.user.first_name %> <%= comment.user.second_name %></p>
    <%= link_to "Edit comment", admin_post_comment_path(@post, comment) %>
    <% end %>
  </ul>
</div>

app/views/comments/index.html.erb
<div>
  <ul>
      <li>
        <h2><%= @post.title %></h2>
      </li>
      <li>
        <p><%= @post.body %></p>
      </li>
      <p> <%= @post.user.first_name %>  <%= @post.user.second_name %></p> 
  </ul>
</div>
<h2> <%= flash[:success] %> </h2>
<div>
  <%= render 'shared/form' %>
<div>
  <ul>
    <% @post.comments.each do |c| %>
      <li>
        <p><%= c.body %></p>
      </li>
        <p><%= c.user.first_name %>  <%= c.user.second_name %></p>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostsV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <div class="container">
    <nav class="d-flex flex-wrap aling-items-center justify-content-center justify-content-lg-start ">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
         <li>
         <% if current_user && current_user.first_name? %>
          <h4><%= "#{current_user.first_name}  #{current_user.second_name}"%></h4>
        <% else %>
        <% end %>
        </li>
        <li>
          <%= link_to 'Home', root_path, class: "nav-link px-5" %>
        </li>
        <% if current_user && current_user.status? %>
        <li>
          <%= link_to 'Admin panel', admin_posts_path, class: "nav-link px-5 mr-10" %>
        </li>
        <li>
          <%= link_to "Create post", new_admin_post_path%>
        </li>
        <% else %>
        <% end %>
        <% if user_signed_in? %>
        <li>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, confirm: "Are you shure?" %>
        </li>
        <li>
          <%= link_to "Update user", edit_user_registration_path %>
        </li>
        <% else %>
        <%= link_to 'Log in', new_user_session_path, class: "nav-link px-5 mr-10" %>
        <% end %>
      </ul>
    </nav>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1> Welcome to PostsV2 </h1>
<h2><%= flash[:alert] %></h2>
<div>
  <ul>
    <% @posts.each do |p| %>
      <li>
        <h2> <%= p.title %></h2>
        <p> <%= p.body %> </p> 
      </li>
      <p> <%= p.user.first_name %>  <%= p.user.second_name %></p> 
      <div>
      <%= link_to "Show", post_comments_path(p) %>
      </div>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= render 'shared/errors', object: @comment %>
 <%= form_with model: [@admin, @post, @comment] do |c| %>
  <%= c.label :body, 'body' %>
  <%= c.text_field :body %>

  <!-- Кнопка отправки формы -->
  <%= c.submit 'Отправить' %>
<% end %>